CREATE TABLE LEAVE_REQUESTS (
    LEAVE_ID NUMBER PRIMARY KEY,
    STUDENT_ID NUMBER,
    LEAVE_TYPE VARCHAR2(50),
    FROM_DATE DATE,
    TO_DATE DATE,
    REASON VARCHAR2(500),
    STATUS VARCHAR2(20) DEFAULT 'Pending',
    FACULTY_REMARK VARCHAR2(500),
    APPLIED_DATE DATE DEFAULT SYSDATE,
    ATTACHMENT VARCHAR2(500),
    PRIORITY VARCHAR2(20),
    TRACKING_ID VARCHAR2(50)
);
